server:
  port: 9000
 
 

spring:
  security:
    user:
      name: wangle
      password: 131452
  application:
    name: lexianghotel-back
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/lexiang_hotel
    username: root
    password: 131452
    dbcp2:
      max-idle: 5
      max-wait-millis: 10000
      min-idle: 5
      initial-size: 5
      
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    jdbc-type-for-null: null
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.lexiang.back.entity.*
  global-config:
    #xml热加载
    refresh: true
